/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class AndroidCsound extends Csound {
  private transient long swigCPtr;

  protected AndroidCsound(long cPtr, boolean cMemoryOwn) {
    super(csndJNI.AndroidCsound_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AndroidCsound obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_AndroidCsound(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AndroidCsound(boolean async) {
    this(csndJNI.new_AndroidCsound__SWIG_0(async), true);
  }

  public AndroidCsound() {
    this(csndJNI.new_AndroidCsound__SWIG_1(), true);
  }

  public void setOpenSlCallbacks() {
    csndJNI.AndroidCsound_setOpenSlCallbacks(swigCPtr, this);
  }

  public int SetGlobalEnv(String name, String variable) {
    return csndJNI.AndroidCsound_SetGlobalEnv(swigCPtr, this, name, variable);
  }

  public long getStreamTime() {
    return csndJNI.AndroidCsound_getStreamTime(swigCPtr, this);
  }

  public void Pause(boolean pause) {
    csndJNI.AndroidCsound_Pause(swigCPtr, this, pause);
  }

  public int GetKcount() {
    return csndJNI.AndroidCsound_GetKcount(swigCPtr, this);
  }

}
