/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public final class controlChannelType {
  public final static controlChannelType CSOUND_CONTROL_CHANNEL = new controlChannelType("CSOUND_CONTROL_CHANNEL", csndJNI.CSOUND_CONTROL_CHANNEL_get());
  public final static controlChannelType CSOUND_AUDIO_CHANNEL = new controlChannelType("CSOUND_AUDIO_CHANNEL", csndJNI.CSOUND_AUDIO_CHANNEL_get());
  public final static controlChannelType CSOUND_STRING_CHANNEL = new controlChannelType("CSOUND_STRING_CHANNEL", csndJNI.CSOUND_STRING_CHANNEL_get());
  public final static controlChannelType CSOUND_PVS_CHANNEL = new controlChannelType("CSOUND_PVS_CHANNEL", csndJNI.CSOUND_PVS_CHANNEL_get());
  public final static controlChannelType CSOUND_VAR_CHANNEL = new controlChannelType("CSOUND_VAR_CHANNEL", csndJNI.CSOUND_VAR_CHANNEL_get());
  public final static controlChannelType CSOUND_CHANNEL_TYPE_MASK = new controlChannelType("CSOUND_CHANNEL_TYPE_MASK", csndJNI.CSOUND_CHANNEL_TYPE_MASK_get());
  public final static controlChannelType CSOUND_INPUT_CHANNEL = new controlChannelType("CSOUND_INPUT_CHANNEL", csndJNI.CSOUND_INPUT_CHANNEL_get());
  public final static controlChannelType CSOUND_OUTPUT_CHANNEL = new controlChannelType("CSOUND_OUTPUT_CHANNEL", csndJNI.CSOUND_OUTPUT_CHANNEL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static controlChannelType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + controlChannelType.class + " with value " + swigValue);
  }

  private controlChannelType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private controlChannelType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private controlChannelType(String swigName, controlChannelType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static controlChannelType[] swigValues = { CSOUND_CONTROL_CHANNEL, CSOUND_AUDIO_CHANNEL, CSOUND_STRING_CHANNEL, CSOUND_PVS_CHANNEL, CSOUND_VAR_CHANNEL, CSOUND_CHANNEL_TYPE_MASK, CSOUND_INPUT_CHANNEL, CSOUND_OUTPUT_CHANNEL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

