/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class controlChannelInfo_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected controlChannelInfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(controlChannelInfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_controlChannelInfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    csndJNI.controlChannelInfo_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return csndJNI.controlChannelInfo_t_name_get(swigCPtr, this);
  }

  public void setType(int value) {
    csndJNI.controlChannelInfo_t_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return csndJNI.controlChannelInfo_t_type_get(swigCPtr, this);
  }

  public void setHints(controlChannelHints_t value) {
    csndJNI.controlChannelInfo_t_hints_set(swigCPtr, this, controlChannelHints_t.getCPtr(value), value);
  }

  public controlChannelHints_t getHints() {
    long cPtr = csndJNI.controlChannelInfo_t_hints_get(swigCPtr, this);
    return (cPtr == 0) ? null : new controlChannelHints_t(cPtr, false);
  }

  public controlChannelInfo_t() {
    this(csndJNI.new_controlChannelInfo_t(), true);
  }

}
