/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public final class controlChannelBehavior {
  public final static controlChannelBehavior CSOUND_CONTROL_CHANNEL_NO_HINTS = new controlChannelBehavior("CSOUND_CONTROL_CHANNEL_NO_HINTS", csndJNI.CSOUND_CONTROL_CHANNEL_NO_HINTS_get());
  public final static controlChannelBehavior CSOUND_CONTROL_CHANNEL_INT = new controlChannelBehavior("CSOUND_CONTROL_CHANNEL_INT", csndJNI.CSOUND_CONTROL_CHANNEL_INT_get());
  public final static controlChannelBehavior CSOUND_CONTROL_CHANNEL_LIN = new controlChannelBehavior("CSOUND_CONTROL_CHANNEL_LIN", csndJNI.CSOUND_CONTROL_CHANNEL_LIN_get());
  public final static controlChannelBehavior CSOUND_CONTROL_CHANNEL_EXP = new controlChannelBehavior("CSOUND_CONTROL_CHANNEL_EXP", csndJNI.CSOUND_CONTROL_CHANNEL_EXP_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static controlChannelBehavior swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + controlChannelBehavior.class + " with value " + swigValue);
  }

  private controlChannelBehavior(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private controlChannelBehavior(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private controlChannelBehavior(String swigName, controlChannelBehavior swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static controlChannelBehavior[] swigValues = { CSOUND_CONTROL_CHANNEL_NO_HINTS, CSOUND_CONTROL_CHANNEL_INT, CSOUND_CONTROL_CHANNEL_LIN, CSOUND_CONTROL_CHANNEL_EXP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

