/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class controlChannelHints_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected controlChannelHints_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(controlChannelHints_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_controlChannelHints_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBehav(controlChannelBehavior value) {
    csndJNI.controlChannelHints_t_behav_set(swigCPtr, this, value.swigValue());
  }

  public controlChannelBehavior getBehav() {
    return controlChannelBehavior.swigToEnum(csndJNI.controlChannelHints_t_behav_get(swigCPtr, this));
  }

  public void setDflt(float value) {
    csndJNI.controlChannelHints_t_dflt_set(swigCPtr, this, value);
  }

  public float getDflt() {
    return csndJNI.controlChannelHints_t_dflt_get(swigCPtr, this);
  }

  public void setMin(float value) {
    csndJNI.controlChannelHints_t_min_set(swigCPtr, this, value);
  }

  public float getMin() {
    return csndJNI.controlChannelHints_t_min_get(swigCPtr, this);
  }

  public void setMax(float value) {
    csndJNI.controlChannelHints_t_max_set(swigCPtr, this, value);
  }

  public float getMax() {
    return csndJNI.controlChannelHints_t_max_get(swigCPtr, this);
  }

  public void setX(int value) {
    csndJNI.controlChannelHints_t_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return csndJNI.controlChannelHints_t_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    csndJNI.controlChannelHints_t_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return csndJNI.controlChannelHints_t_y_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    csndJNI.controlChannelHints_t_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return csndJNI.controlChannelHints_t_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    csndJNI.controlChannelHints_t_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return csndJNI.controlChannelHints_t_height_get(swigCPtr, this);
  }

  public void setAttributes(String value) {
    csndJNI.controlChannelHints_t_attributes_set(swigCPtr, this, value);
  }

  public String getAttributes() {
    return csndJNI.controlChannelHints_t_attributes_get(swigCPtr, this);
  }

  public controlChannelHints_t() {
    this(csndJNI.new_controlChannelHints_t(), true);
  }

}
