/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class csCfgVariable_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected csCfgVariable_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(csCfgVariable_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_csCfgVariable_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setH(csCfgVariableHead_t value) {
    csndJNI.csCfgVariable_t_h_set(swigCPtr, this, csCfgVariableHead_t.getCPtr(value), value);
  }

  public csCfgVariableHead_t getH() {
    long cPtr = csndJNI.csCfgVariable_t_h_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableHead_t(cPtr, false);
  }

  public void setI(csCfgVariableInt_t value) {
    csndJNI.csCfgVariable_t_i_set(swigCPtr, this, csCfgVariableInt_t.getCPtr(value), value);
  }

  public csCfgVariableInt_t getI() {
    long cPtr = csndJNI.csCfgVariable_t_i_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableInt_t(cPtr, false);
  }

  public void setB(csCfgVariableBoolean_t value) {
    csndJNI.csCfgVariable_t_b_set(swigCPtr, this, csCfgVariableBoolean_t.getCPtr(value), value);
  }

  public csCfgVariableBoolean_t getB() {
    long cPtr = csndJNI.csCfgVariable_t_b_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableBoolean_t(cPtr, false);
  }

  public void setF(csCfgVariableFloat_t value) {
    csndJNI.csCfgVariable_t_f_set(swigCPtr, this, csCfgVariableFloat_t.getCPtr(value), value);
  }

  public csCfgVariableFloat_t getF() {
    long cPtr = csndJNI.csCfgVariable_t_f_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableFloat_t(cPtr, false);
  }

  public void setD(csCfgVariableDouble_t value) {
    csndJNI.csCfgVariable_t_d_set(swigCPtr, this, csCfgVariableDouble_t.getCPtr(value), value);
  }

  public csCfgVariableDouble_t getD() {
    long cPtr = csndJNI.csCfgVariable_t_d_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableDouble_t(cPtr, false);
  }

  public void setM(csCfgVariableMYFLT_t value) {
    csndJNI.csCfgVariable_t_m_set(swigCPtr, this, csCfgVariableMYFLT_t.getCPtr(value), value);
  }

  public csCfgVariableMYFLT_t getM() {
    long cPtr = csndJNI.csCfgVariable_t_m_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableMYFLT_t(cPtr, false);
  }

  public void setS(csCfgVariableString_t value) {
    csndJNI.csCfgVariable_t_s_set(swigCPtr, this, csCfgVariableString_t.getCPtr(value), value);
  }

  public csCfgVariableString_t getS() {
    long cPtr = csndJNI.csCfgVariable_t_s_get(swigCPtr, this);
    return (cPtr == 0) ? null : new csCfgVariableString_t(cPtr, false);
  }

  public csCfgVariable_t() {
    this(csndJNI.new_csCfgVariable_t(), true);
  }

}
