/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundMidiOutputBuffer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundMidiOutputBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundMidiOutputBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundMidiOutputBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CsoundMidiOutputBuffer(SWIGTYPE_p_unsigned_char buf, int bufSize) {
    this(csndJNI.new_CsoundMidiOutputBuffer(SWIGTYPE_p_unsigned_char.getCPtr(buf), bufSize), true);
  }

  public int PopMessage() {
    return csndJNI.CsoundMidiOutputBuffer_PopMessage(swigCPtr, this);
  }

  public int GetStatus() {
    return csndJNI.CsoundMidiOutputBuffer_GetStatus(swigCPtr, this);
  }

  public int GetChannel() {
    return csndJNI.CsoundMidiOutputBuffer_GetChannel(swigCPtr, this);
  }

  public int GetData1() {
    return csndJNI.CsoundMidiOutputBuffer_GetData1(swigCPtr, this);
  }

  public int GetData2() {
    return csndJNI.CsoundMidiOutputBuffer_GetData2(swigCPtr, this);
  }

}
