/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundChannelList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundChannelList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundChannelList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundChannelList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int Count() {
    return csndJNI.CsoundChannelList_Count(swigCPtr, this);
  }

  public String Name(int ndx) {
    return csndJNI.CsoundChannelList_Name(swigCPtr, this, ndx);
  }

  public int Type(int ndx) {
    return csndJNI.CsoundChannelList_Type(swigCPtr, this, ndx);
  }

  public int IsControlChannel(int ndx) {
    return csndJNI.CsoundChannelList_IsControlChannel(swigCPtr, this, ndx);
  }

  public int IsAudioChannel(int ndx) {
    return csndJNI.CsoundChannelList_IsAudioChannel(swigCPtr, this, ndx);
  }

  public int IsStringChannel(int ndx) {
    return csndJNI.CsoundChannelList_IsStringChannel(swigCPtr, this, ndx);
  }

  public int IsInputChannel(int ndx) {
    return csndJNI.CsoundChannelList_IsInputChannel(swigCPtr, this, ndx);
  }

  public int IsOutputChannel(int ndx) {
    return csndJNI.CsoundChannelList_IsOutputChannel(swigCPtr, this, ndx);
  }

  public int SubType(int ndx) {
    return csndJNI.CsoundChannelList_SubType(swigCPtr, this, ndx);
  }

  public double DefaultValue(int ndx) {
    return csndJNI.CsoundChannelList_DefaultValue(swigCPtr, this, ndx);
  }

  public double MinValue(int ndx) {
    return csndJNI.CsoundChannelList_MinValue(swigCPtr, this, ndx);
  }

  public double MaxValue(int ndx) {
    return csndJNI.CsoundChannelList_MaxValue(swigCPtr, this, ndx);
  }

  public void Clear() {
    csndJNI.CsoundChannelList_Clear(swigCPtr, this);
  }

  public CsoundChannelList(SWIGTYPE_p_CSOUND_ csound) {
    this(csndJNI.new_CsoundChannelList__SWIG_0(SWIGTYPE_p_CSOUND_.getCPtr(csound)), true);
  }

  public CsoundChannelList(Csound csound) {
    this(csndJNI.new_CsoundChannelList__SWIG_1(Csound.getCPtr(csound), csound), true);
  }

}
