/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CSOUND_PARAMS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CSOUND_PARAMS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CSOUND_PARAMS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CSOUND_PARAMS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDebug_mode(int value) {
    csndJNI.CSOUND_PARAMS_debug_mode_set(swigCPtr, this, value);
  }

  public int getDebug_mode() {
    return csndJNI.CSOUND_PARAMS_debug_mode_get(swigCPtr, this);
  }

  public void setBuffer_frames(int value) {
    csndJNI.CSOUND_PARAMS_buffer_frames_set(swigCPtr, this, value);
  }

  public int getBuffer_frames() {
    return csndJNI.CSOUND_PARAMS_buffer_frames_get(swigCPtr, this);
  }

  public void setHardware_buffer_frames(int value) {
    csndJNI.CSOUND_PARAMS_hardware_buffer_frames_set(swigCPtr, this, value);
  }

  public int getHardware_buffer_frames() {
    return csndJNI.CSOUND_PARAMS_hardware_buffer_frames_get(swigCPtr, this);
  }

  public void setDisplays(int value) {
    csndJNI.CSOUND_PARAMS_displays_set(swigCPtr, this, value);
  }

  public int getDisplays() {
    return csndJNI.CSOUND_PARAMS_displays_get(swigCPtr, this);
  }

  public void setAscii_graphs(int value) {
    csndJNI.CSOUND_PARAMS_ascii_graphs_set(swigCPtr, this, value);
  }

  public int getAscii_graphs() {
    return csndJNI.CSOUND_PARAMS_ascii_graphs_get(swigCPtr, this);
  }

  public void setPostscript_graphs(int value) {
    csndJNI.CSOUND_PARAMS_postscript_graphs_set(swigCPtr, this, value);
  }

  public int getPostscript_graphs() {
    return csndJNI.CSOUND_PARAMS_postscript_graphs_get(swigCPtr, this);
  }

  public void setMessage_level(int value) {
    csndJNI.CSOUND_PARAMS_message_level_set(swigCPtr, this, value);
  }

  public int getMessage_level() {
    return csndJNI.CSOUND_PARAMS_message_level_get(swigCPtr, this);
  }

  public void setTempo(int value) {
    csndJNI.CSOUND_PARAMS_tempo_set(swigCPtr, this, value);
  }

  public int getTempo() {
    return csndJNI.CSOUND_PARAMS_tempo_get(swigCPtr, this);
  }

  public void setRing_bell(int value) {
    csndJNI.CSOUND_PARAMS_ring_bell_set(swigCPtr, this, value);
  }

  public int getRing_bell() {
    return csndJNI.CSOUND_PARAMS_ring_bell_get(swigCPtr, this);
  }

  public void setUse_cscore(int value) {
    csndJNI.CSOUND_PARAMS_use_cscore_set(swigCPtr, this, value);
  }

  public int getUse_cscore() {
    return csndJNI.CSOUND_PARAMS_use_cscore_get(swigCPtr, this);
  }

  public void setTerminate_on_midi(int value) {
    csndJNI.CSOUND_PARAMS_terminate_on_midi_set(swigCPtr, this, value);
  }

  public int getTerminate_on_midi() {
    return csndJNI.CSOUND_PARAMS_terminate_on_midi_get(swigCPtr, this);
  }

  public void setHeartbeat(int value) {
    csndJNI.CSOUND_PARAMS_heartbeat_set(swigCPtr, this, value);
  }

  public int getHeartbeat() {
    return csndJNI.CSOUND_PARAMS_heartbeat_get(swigCPtr, this);
  }

  public void setDefer_gen01_load(int value) {
    csndJNI.CSOUND_PARAMS_defer_gen01_load_set(swigCPtr, this, value);
  }

  public int getDefer_gen01_load() {
    return csndJNI.CSOUND_PARAMS_defer_gen01_load_get(swigCPtr, this);
  }

  public void setMidi_key(int value) {
    csndJNI.CSOUND_PARAMS_midi_key_set(swigCPtr, this, value);
  }

  public int getMidi_key() {
    return csndJNI.CSOUND_PARAMS_midi_key_get(swigCPtr, this);
  }

  public void setMidi_key_cps(int value) {
    csndJNI.CSOUND_PARAMS_midi_key_cps_set(swigCPtr, this, value);
  }

  public int getMidi_key_cps() {
    return csndJNI.CSOUND_PARAMS_midi_key_cps_get(swigCPtr, this);
  }

  public void setMidi_key_oct(int value) {
    csndJNI.CSOUND_PARAMS_midi_key_oct_set(swigCPtr, this, value);
  }

  public int getMidi_key_oct() {
    return csndJNI.CSOUND_PARAMS_midi_key_oct_get(swigCPtr, this);
  }

  public void setMidi_key_pch(int value) {
    csndJNI.CSOUND_PARAMS_midi_key_pch_set(swigCPtr, this, value);
  }

  public int getMidi_key_pch() {
    return csndJNI.CSOUND_PARAMS_midi_key_pch_get(swigCPtr, this);
  }

  public void setMidi_velocity(int value) {
    csndJNI.CSOUND_PARAMS_midi_velocity_set(swigCPtr, this, value);
  }

  public int getMidi_velocity() {
    return csndJNI.CSOUND_PARAMS_midi_velocity_get(swigCPtr, this);
  }

  public void setMidi_velocity_amp(int value) {
    csndJNI.CSOUND_PARAMS_midi_velocity_amp_set(swigCPtr, this, value);
  }

  public int getMidi_velocity_amp() {
    return csndJNI.CSOUND_PARAMS_midi_velocity_amp_get(swigCPtr, this);
  }

  public void setNo_default_paths(int value) {
    csndJNI.CSOUND_PARAMS_no_default_paths_set(swigCPtr, this, value);
  }

  public int getNo_default_paths() {
    return csndJNI.CSOUND_PARAMS_no_default_paths_get(swigCPtr, this);
  }

  public void setNumber_of_threads(int value) {
    csndJNI.CSOUND_PARAMS_number_of_threads_set(swigCPtr, this, value);
  }

  public int getNumber_of_threads() {
    return csndJNI.CSOUND_PARAMS_number_of_threads_get(swigCPtr, this);
  }

  public void setSyntax_check_only(int value) {
    csndJNI.CSOUND_PARAMS_syntax_check_only_set(swigCPtr, this, value);
  }

  public int getSyntax_check_only() {
    return csndJNI.CSOUND_PARAMS_syntax_check_only_get(swigCPtr, this);
  }

  public void setCsd_line_counts(int value) {
    csndJNI.CSOUND_PARAMS_csd_line_counts_set(swigCPtr, this, value);
  }

  public int getCsd_line_counts() {
    return csndJNI.CSOUND_PARAMS_csd_line_counts_get(swigCPtr, this);
  }

  public void setCompute_weights(int value) {
    csndJNI.CSOUND_PARAMS_compute_weights_set(swigCPtr, this, value);
  }

  public int getCompute_weights() {
    return csndJNI.CSOUND_PARAMS_compute_weights_get(swigCPtr, this);
  }

  public void setRealtime_mode(int value) {
    csndJNI.CSOUND_PARAMS_realtime_mode_set(swigCPtr, this, value);
  }

  public int getRealtime_mode() {
    return csndJNI.CSOUND_PARAMS_realtime_mode_get(swigCPtr, this);
  }

  public void setSample_accurate(int value) {
    csndJNI.CSOUND_PARAMS_sample_accurate_set(swigCPtr, this, value);
  }

  public int getSample_accurate() {
    return csndJNI.CSOUND_PARAMS_sample_accurate_get(swigCPtr, this);
  }

  public void setSample_rate_override(float value) {
    csndJNI.CSOUND_PARAMS_sample_rate_override_set(swigCPtr, this, value);
  }

  public float getSample_rate_override() {
    return csndJNI.CSOUND_PARAMS_sample_rate_override_get(swigCPtr, this);
  }

  public void setControl_rate_override(float value) {
    csndJNI.CSOUND_PARAMS_control_rate_override_set(swigCPtr, this, value);
  }

  public float getControl_rate_override() {
    return csndJNI.CSOUND_PARAMS_control_rate_override_get(swigCPtr, this);
  }

  public void setNchnls_override(int value) {
    csndJNI.CSOUND_PARAMS_nchnls_override_set(swigCPtr, this, value);
  }

  public int getNchnls_override() {
    return csndJNI.CSOUND_PARAMS_nchnls_override_get(swigCPtr, this);
  }

  public void setNchnls_i_override(int value) {
    csndJNI.CSOUND_PARAMS_nchnls_i_override_set(swigCPtr, this, value);
  }

  public int getNchnls_i_override() {
    return csndJNI.CSOUND_PARAMS_nchnls_i_override_get(swigCPtr, this);
  }

  public void setE0dbfs_override(float value) {
    csndJNI.CSOUND_PARAMS_e0dbfs_override_set(swigCPtr, this, value);
  }

  public float getE0dbfs_override() {
    return csndJNI.CSOUND_PARAMS_e0dbfs_override_get(swigCPtr, this);
  }

  public void setDaemon(int value) {
    csndJNI.CSOUND_PARAMS_daemon_set(swigCPtr, this, value);
  }

  public int getDaemon() {
    return csndJNI.CSOUND_PARAMS_daemon_get(swigCPtr, this);
  }

  public void setKsmps_override(int value) {
    csndJNI.CSOUND_PARAMS_ksmps_override_set(swigCPtr, this, value);
  }

  public int getKsmps_override() {
    return csndJNI.CSOUND_PARAMS_ksmps_override_get(swigCPtr, this);
  }

  public CSOUND_PARAMS() {
    this(csndJNI.new_CSOUND_PARAMS(), true);
  }

}
