/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundCallbackWrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundCallbackWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundCallbackWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundCallbackWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    csndJNI.CsoundCallbackWrapper_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    csndJNI.CsoundCallbackWrapper_change_ownership(this, swigCPtr, true);
  }

  public void MessageCallback(int attr, String msg) {
    if (getClass() == CsoundCallbackWrapper.class) csndJNI.CsoundCallbackWrapper_MessageCallback(swigCPtr, this, attr, msg); else csndJNI.CsoundCallbackWrapper_MessageCallbackSwigExplicitCsoundCallbackWrapper(swigCPtr, this, attr, msg);
  }

  public double InputValueCallback(String chnName) {
    return (getClass() == CsoundCallbackWrapper.class) ? csndJNI.CsoundCallbackWrapper_InputValueCallback(swigCPtr, this, chnName) : csndJNI.CsoundCallbackWrapper_InputValueCallbackSwigExplicitCsoundCallbackWrapper(swigCPtr, this, chnName);
  }

  public void OutputValueCallback(String chnName, double value) {
    if (getClass() == CsoundCallbackWrapper.class) csndJNI.CsoundCallbackWrapper_OutputValueCallback(swigCPtr, this, chnName, value); else csndJNI.CsoundCallbackWrapper_OutputValueCallbackSwigExplicitCsoundCallbackWrapper(swigCPtr, this, chnName, value);
  }

  public int YieldCallback() {
    return (getClass() == CsoundCallbackWrapper.class) ? csndJNI.CsoundCallbackWrapper_YieldCallback(swigCPtr, this) : csndJNI.CsoundCallbackWrapper_YieldCallbackSwigExplicitCsoundCallbackWrapper(swigCPtr, this);
  }

  public void MidiInputCallback(CsoundMidiInputBuffer p) {
    if (getClass() == CsoundCallbackWrapper.class) csndJNI.CsoundCallbackWrapper_MidiInputCallback(swigCPtr, this, CsoundMidiInputBuffer.getCPtr(p), p); else csndJNI.CsoundCallbackWrapper_MidiInputCallbackSwigExplicitCsoundCallbackWrapper(swigCPtr, this, CsoundMidiInputBuffer.getCPtr(p), p);
  }

  public void MidiOutputCallback(CsoundMidiOutputBuffer p) {
    if (getClass() == CsoundCallbackWrapper.class) csndJNI.CsoundCallbackWrapper_MidiOutputCallback(swigCPtr, this, CsoundMidiOutputBuffer.getCPtr(p), p); else csndJNI.CsoundCallbackWrapper_MidiOutputCallbackSwigExplicitCsoundCallbackWrapper(swigCPtr, this, CsoundMidiOutputBuffer.getCPtr(p), p);
  }

  public void SetMessageCallback() {
    csndJNI.CsoundCallbackWrapper_SetMessageCallback(swigCPtr, this);
  }

  public void SetYieldCallback() {
    csndJNI.CsoundCallbackWrapper_SetYieldCallback(swigCPtr, this);
  }

  public void SetMidiInputCallback(CsoundArgVList argv) {
    csndJNI.CsoundCallbackWrapper_SetMidiInputCallback(swigCPtr, this, CsoundArgVList.getCPtr(argv), argv);
  }

  public void SetMidiOutputCallback(CsoundArgVList argv) {
    csndJNI.CsoundCallbackWrapper_SetMidiOutputCallback(swigCPtr, this, CsoundArgVList.getCPtr(argv), argv);
  }

  public SWIGTYPE_p_CSOUND_ GetCsound() {
    long cPtr = csndJNI.CsoundCallbackWrapper_GetCsound(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CSOUND_(cPtr, false);
  }

  public static String CharPtrToString(String s) {
    return csndJNI.CsoundCallbackWrapper_CharPtrToString(s);
  }

  public CsoundCallbackWrapper(Csound csound) {
    this(csndJNI.new_CsoundCallbackWrapper__SWIG_0(Csound.getCPtr(csound), csound), true);
    csndJNI.CsoundCallbackWrapper_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public CsoundCallbackWrapper(SWIGTYPE_p_CSOUND_ csound) {
    this(csndJNI.new_CsoundCallbackWrapper__SWIG_1(SWIGTYPE_p_CSOUND_.getCPtr(csound)), true);
    csndJNI.CsoundCallbackWrapper_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
