/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundMYFLTArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundMYFLTArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundMYFLTArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundMYFLTArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_p_float GetPtr() {
    long cPtr = csndJNI.CsoundMYFLTArray_GetPtr__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_float(cPtr, false);
  }

  public SWIGTYPE_p_float GetPtr(int ndx) {
    long cPtr = csndJNI.CsoundMYFLTArray_GetPtr__SWIG_1(swigCPtr, this, ndx);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void SetPtr(SWIGTYPE_p_float ptr) {
    csndJNI.CsoundMYFLTArray_SetPtr(swigCPtr, this, SWIGTYPE_p_float.getCPtr(ptr));
  }

  public void SetValue(int ndx, double value) {
    csndJNI.CsoundMYFLTArray_SetValue(swigCPtr, this, ndx, value);
  }

  public void SetValues(int ndx, double v0, double v1) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_0(swigCPtr, this, ndx, v0, v1);
  }

  public void SetValues(int ndx, double v0, double v1, double v2) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_1(swigCPtr, this, ndx, v0, v1, v2);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_2(swigCPtr, this, ndx, v0, v1, v2, v3);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3, double v4) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_3(swigCPtr, this, ndx, v0, v1, v2, v3, v4);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3, double v4, double v5) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_4(swigCPtr, this, ndx, v0, v1, v2, v3, v4, v5);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3, double v4, double v5, double v6) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_5(swigCPtr, this, ndx, v0, v1, v2, v3, v4, v5, v6);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3, double v4, double v5, double v6, double v7) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_6(swigCPtr, this, ndx, v0, v1, v2, v3, v4, v5, v6, v7);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3, double v4, double v5, double v6, double v7, double v8) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_7(swigCPtr, this, ndx, v0, v1, v2, v3, v4, v5, v6, v7, v8);
  }

  public void SetValues(int ndx, double v0, double v1, double v2, double v3, double v4, double v5, double v6, double v7, double v8, double v9) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_8(swigCPtr, this, ndx, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9);
  }

  public double GetValue(int ndx) {
    return csndJNI.CsoundMYFLTArray_GetValue(swigCPtr, this, ndx);
  }

  public void SetValues(int ndx, int n, SWIGTYPE_p_float src) {
    csndJNI.CsoundMYFLTArray_SetValues__SWIG_9(swigCPtr, this, ndx, n, SWIGTYPE_p_float.getCPtr(src));
  }

  public void GetValues(SWIGTYPE_p_float dst, int ndx, int n) {
    csndJNI.CsoundMYFLTArray_GetValues(swigCPtr, this, SWIGTYPE_p_float.getCPtr(dst), ndx, n);
  }

  public void SetStringValue(String s, int maxLen) {
    csndJNI.CsoundMYFLTArray_SetStringValue(swigCPtr, this, s, maxLen);
  }

  public String GetStringValue() {
    return csndJNI.CsoundMYFLTArray_GetStringValue(swigCPtr, this);
  }

  public void Clear() {
    csndJNI.CsoundMYFLTArray_Clear(swigCPtr, this);
  }

  public CsoundMYFLTArray() {
    this(csndJNI.new_CsoundMYFLTArray__SWIG_0(), true);
  }

  public CsoundMYFLTArray(int n) {
    this(csndJNI.new_CsoundMYFLTArray__SWIG_1(n), true);
  }

}
