/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class Csound {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Csound(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Csound obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_Csound(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPydata(SWIGTYPE_p_void value) {
    csndJNI.Csound_pydata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPydata() {
    long cPtr = csndJNI.Csound_pydata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_CSOUND_ GetCsound() {
    long cPtr = csndJNI.Csound_GetCsound(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CSOUND_(cPtr, false);
  }

  public int InitializeCscore(SWIGTYPE_p_FILE insco, SWIGTYPE_p_FILE outsco) {
    return csndJNI.Csound_InitializeCscore(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(insco), SWIGTYPE_p_FILE.getCPtr(outsco));
  }

  public int GetVersion() {
    return csndJNI.Csound_GetVersion(swigCPtr, this);
  }

  public int GetAPIVersion() {
    return csndJNI.Csound_GetAPIVersion(swigCPtr, this);
  }

  public String GetEnv(String name) {
    return csndJNI.Csound_GetEnv(swigCPtr, this, name);
  }

  public int SetGlobalEnv(String name, String value) {
    return csndJNI.Csound_SetGlobalEnv(swigCPtr, this, name, value);
  }

  public int SetOption(String option) {
    return csndJNI.Csound_SetOption(swigCPtr, this, option);
  }

  public void SetParams(CSOUND_PARAMS p) {
    csndJNI.Csound_SetParams(swigCPtr, this, CSOUND_PARAMS.getCPtr(p), p);
  }

  public void GetParams(CSOUND_PARAMS p) {
    csndJNI.Csound_GetParams(swigCPtr, this, CSOUND_PARAMS.getCPtr(p), p);
  }

  public void SetOutput(String name, String type, String format) {
    csndJNI.Csound_SetOutput(swigCPtr, this, name, type, format);
  }

  public void SetInput(String name) {
    csndJNI.Csound_SetInput(swigCPtr, this, name);
  }

  public void SetMIDIInput(String name) {
    csndJNI.Csound_SetMIDIInput(swigCPtr, this, name);
  }

  public void SetMIDIFileInput(String name) {
    csndJNI.Csound_SetMIDIFileInput(swigCPtr, this, name);
  }

  public void SetMIDIOutput(String name) {
    csndJNI.Csound_SetMIDIOutput(swigCPtr, this, name);
  }

  public void SetMIDIFileOutput(String name) {
    csndJNI.Csound_SetMIDIFileOutput(swigCPtr, this, name);
  }

  public TREE ParseOrc(String str) {
    long cPtr = csndJNI.Csound_ParseOrc(swigCPtr, this, str);
    return (cPtr == 0) ? null : new TREE(cPtr, false);
  }

  public int CompileTree(TREE root) {
    return csndJNI.Csound_CompileTree(swigCPtr, this, TREE.getCPtr(root), root);
  }

  public void DeleteTree(TREE root) {
    csndJNI.Csound_DeleteTree(swigCPtr, this, TREE.getCPtr(root), root);
  }

  public int CompileOrc(String str) {
    return csndJNI.Csound_CompileOrc(swigCPtr, this, str);
  }

  public float EvalCode(String str) {
    return csndJNI.Csound_EvalCode(swigCPtr, this, str);
  }

  public int ReadScore(String str) {
    return csndJNI.Csound_ReadScore(swigCPtr, this, str);
  }

  public int CompileArgs(int argc, SWIGTYPE_p_p_char argv) {
    return csndJNI.Csound_CompileArgs(swigCPtr, this, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public int Start(SWIGTYPE_p_CSOUND_ csound) {
    return csndJNI.Csound_Start__SWIG_0(swigCPtr, this, SWIGTYPE_p_CSOUND_.getCPtr(csound));
  }

  public int Compile(int argc, SWIGTYPE_p_p_char argv) {
    return csndJNI.Csound_Compile__SWIG_0(swigCPtr, this, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public int Compile(String csdName) {
    return csndJNI.Csound_Compile__SWIG_1(swigCPtr, this, csdName);
  }

  public int Compile(String orcName, String scoName) {
    return csndJNI.Csound_Compile__SWIG_2(swigCPtr, this, orcName, scoName);
  }

  public int Compile(String arg1, String arg2, String arg3) {
    return csndJNI.Csound_Compile__SWIG_3(swigCPtr, this, arg1, arg2, arg3);
  }

  public int Compile(String arg1, String arg2, String arg3, String arg4) {
    return csndJNI.Csound_Compile__SWIG_4(swigCPtr, this, arg1, arg2, arg3, arg4);
  }

  public int Compile(String arg1, String arg2, String arg3, String arg4, String arg5) {
    return csndJNI.Csound_Compile__SWIG_5(swigCPtr, this, arg1, arg2, arg3, arg4, arg5);
  }

  public int CompileCsd(String csd) {
    return csndJNI.Csound_CompileCsd(swigCPtr, this, csd);
  }

  public int Start() {
    return csndJNI.Csound_Start__SWIG_1(swigCPtr, this);
  }

  public int Perform() {
    return csndJNI.Csound_Perform__SWIG_0(swigCPtr, this);
  }

  public int Perform(int argc, SWIGTYPE_p_p_char argv) {
    return csndJNI.Csound_Perform__SWIG_1(swigCPtr, this, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public int Perform(String csdName) {
    return csndJNI.Csound_Perform__SWIG_2(swigCPtr, this, csdName);
  }

  public int Perform(String orcName, String scoName) {
    return csndJNI.Csound_Perform__SWIG_3(swigCPtr, this, orcName, scoName);
  }

  public int Perform(String arg1, String arg2, String arg3) {
    return csndJNI.Csound_Perform__SWIG_4(swigCPtr, this, arg1, arg2, arg3);
  }

  public int Perform(String arg1, String arg2, String arg3, String arg4) {
    return csndJNI.Csound_Perform__SWIG_5(swigCPtr, this, arg1, arg2, arg3, arg4);
  }

  public int Perform(String arg1, String arg2, String arg3, String arg4, String arg5) {
    return csndJNI.Csound_Perform__SWIG_6(swigCPtr, this, arg1, arg2, arg3, arg4, arg5);
  }

  public int PerformKsmps() {
    return csndJNI.Csound_PerformKsmps(swigCPtr, this);
  }

  public int PerformBuffer() {
    return csndJNI.Csound_PerformBuffer(swigCPtr, this);
  }

  public void Stop() {
    csndJNI.Csound_Stop(swigCPtr, this);
  }

  public int Cleanup() {
    return csndJNI.Csound_Cleanup(swigCPtr, this);
  }

  public void Reset() {
    csndJNI.Csound_Reset(swigCPtr, this);
  }

  public float GetSr() {
    return csndJNI.Csound_GetSr(swigCPtr, this);
  }

  public float GetKr() {
    return csndJNI.Csound_GetKr(swigCPtr, this);
  }

  public int GetKsmps() {
    return csndJNI.Csound_GetKsmps(swigCPtr, this);
  }

  public int GetNchnls() {
    return csndJNI.Csound_GetNchnls(swigCPtr, this);
  }

  public int GetNchnlsInput() {
    return csndJNI.Csound_GetNchnlsInput(swigCPtr, this);
  }

  public float Get0dBFS() {
    return csndJNI.Csound_Get0dBFS(swigCPtr, this);
  }

  public int GetInputBufferSize() {
    return csndJNI.Csound_GetInputBufferSize(swigCPtr, this);
  }

  public int GetOutputBufferSize() {
    return csndJNI.Csound_GetOutputBufferSize(swigCPtr, this);
  }

  public SWIGTYPE_p_float GetInputBuffer() {
    long cPtr = csndJNI.Csound_GetInputBuffer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public SWIGTYPE_p_float GetOutputBuffer() {
    long cPtr = csndJNI.Csound_GetOutputBuffer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public SWIGTYPE_p_float GetSpin() {
    long cPtr = csndJNI.Csound_GetSpin(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public SWIGTYPE_p_float GetSpout() {
    long cPtr = csndJNI.Csound_GetSpout(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public String GetOutputName() {
    return csndJNI.Csound_GetOutputName(swigCPtr, this);
  }

  public int GetCurrentTimeSamples() {
    return csndJNI.Csound_GetCurrentTimeSamples(swigCPtr, this);
  }

  public void SetHostImplementedAudioIO(int state, int bufSize) {
    csndJNI.Csound_SetHostImplementedAudioIO(swigCPtr, this, state, bufSize);
  }

  public void SetHostImplementedMIDIIO(int state) {
    csndJNI.Csound_SetHostImplementedMIDIIO(swigCPtr, this, state);
  }

  public double GetScoreTime() {
    return csndJNI.Csound_GetScoreTime(swigCPtr, this);
  }

  public int IsScorePending() {
    return csndJNI.Csound_IsScorePending(swigCPtr, this);
  }

  public void SetScorePending(int pending) {
    csndJNI.Csound_SetScorePending(swigCPtr, this, pending);
  }

  public float GetScoreOffsetSeconds() {
    return csndJNI.Csound_GetScoreOffsetSeconds(swigCPtr, this);
  }

  public void SetScoreOffsetSeconds(double time) {
    csndJNI.Csound_SetScoreOffsetSeconds(swigCPtr, this, time);
  }

  public void RewindScore() {
    csndJNI.Csound_RewindScore(swigCPtr, this);
  }

  public int ScoreSort(SWIGTYPE_p_FILE inFile, SWIGTYPE_p_FILE outFile) {
    return csndJNI.Csound_ScoreSort(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(inFile), SWIGTYPE_p_FILE.getCPtr(outFile));
  }

  public int ScoreExtract(SWIGTYPE_p_FILE inFile, SWIGTYPE_p_FILE outFile, SWIGTYPE_p_FILE extractFile) {
    return csndJNI.Csound_ScoreExtract(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(inFile), SWIGTYPE_p_FILE.getCPtr(outFile), SWIGTYPE_p_FILE.getCPtr(extractFile));
  }

  public void Message(String format) {
    csndJNI.Csound_Message(swigCPtr, this, format);
  }

  public void MessageS(int attr, String format) {
    csndJNI.Csound_MessageS(swigCPtr, this, attr, format);
  }

  public void SetMessageCallback(SWIGTYPE_p_f_p_CSOUND__int_p_q_const__char_va_list__void csoundMessageCallback_) {
    csndJNI.Csound_SetMessageCallback(swigCPtr, this, SWIGTYPE_p_f_p_CSOUND__int_p_q_const__char_va_list__void.getCPtr(csoundMessageCallback_));
  }

  public int GetMessageLevel() {
    return csndJNI.Csound_GetMessageLevel(swigCPtr, this);
  }

  public void SetMessageLevel(int messageLevel) {
    csndJNI.Csound_SetMessageLevel(swigCPtr, this, messageLevel);
  }

  public void InputMessage(String message) {
    csndJNI.Csound_InputMessage(swigCPtr, this, message);
  }

  public void KeyPressed(char c) {
    csndJNI.Csound_KeyPressed(swigCPtr, this, c);
  }

  public int ScoreEvent(char type, SWIGTYPE_p_float pFields, int numFields) {
    return csndJNI.Csound_ScoreEvent(swigCPtr, this, type, SWIGTYPE_p_float.getCPtr(pFields), numFields);
  }

  public int ScoreEventAbsolute(char type, SWIGTYPE_p_float pFields, int numFields, double time_ofs) {
    return csndJNI.Csound_ScoreEventAbsolute(swigCPtr, this, type, SWIGTYPE_p_float.getCPtr(pFields), numFields, time_ofs);
  }

  public void SetExternalMidiInOpenCallback(SWIGTYPE_p_f_p_CSOUND__p_p_void_p_q_const__char__int func) {
    csndJNI.Csound_SetExternalMidiInOpenCallback(swigCPtr, this, SWIGTYPE_p_f_p_CSOUND__p_p_void_p_q_const__char__int.getCPtr(func));
  }

  public void SetExternalMidiReadCallback(SWIGTYPE_p_f_p_CSOUND__p_void_p_unsigned_char_int__int func) {
    csndJNI.Csound_SetExternalMidiReadCallback(swigCPtr, this, SWIGTYPE_p_f_p_CSOUND__p_void_p_unsigned_char_int__int.getCPtr(func));
  }

  public void SetExternalMidiInCloseCallback(SWIGTYPE_p_f_p_CSOUND__p_void__int func) {
    csndJNI.Csound_SetExternalMidiInCloseCallback(swigCPtr, this, SWIGTYPE_p_f_p_CSOUND__p_void__int.getCPtr(func));
  }

  public int NewOpcodeList(SWIGTYPE_p_p_opcodeListEntry opcodelist) {
    return csndJNI.Csound_NewOpcodeList(swigCPtr, this, SWIGTYPE_p_p_opcodeListEntry.getCPtr(opcodelist));
  }

  public void DisposeOpcodeList(opcodeListEntry opcodelist) {
    csndJNI.Csound_DisposeOpcodeList(swigCPtr, this, opcodeListEntry.getCPtr(opcodelist), opcodelist);
  }

  public int AppendOpcode(String opname, int dsblksiz, int flags, int thread, String outypes, String intypes, SWIGTYPE_p_f_p_CSOUND__p_void__int iopadr, SWIGTYPE_p_f_p_CSOUND__p_void__int kopadr, SWIGTYPE_p_f_p_CSOUND__p_void__int aopadr) {
    return csndJNI.Csound_AppendOpcode(swigCPtr, this, opname, dsblksiz, flags, thread, outypes, intypes, SWIGTYPE_p_f_p_CSOUND__p_void__int.getCPtr(iopadr), SWIGTYPE_p_f_p_CSOUND__p_void__int.getCPtr(kopadr), SWIGTYPE_p_f_p_CSOUND__p_void__int.getCPtr(aopadr));
  }

  public int GetDebug() {
    return csndJNI.Csound_GetDebug(swigCPtr, this);
  }

  public void SetDebug(int debug) {
    csndJNI.Csound_SetDebug(swigCPtr, this, debug);
  }

  public int TableLength(int table) {
    return csndJNI.Csound_TableLength(swigCPtr, this, table);
  }

  public float TableGet(int table, int index) {
    return csndJNI.Csound_TableGet(swigCPtr, this, table, index);
  }

  public void TableSet(int table, int index, double value) {
    csndJNI.Csound_TableSet(swigCPtr, this, table, index, value);
  }

  public int GetTable(SWIGTYPE_p_p_float tablePtr, int tableNum) {
    return csndJNI.Csound_GetTable(swigCPtr, this, SWIGTYPE_p_p_float.getCPtr(tablePtr), tableNum);
  }

  public void TableCopyOut(int table, SWIGTYPE_p_float dest) {
    csndJNI.Csound_TableCopyOut(swigCPtr, this, table, SWIGTYPE_p_float.getCPtr(dest));
  }

  public void TableCopyIn(int table, SWIGTYPE_p_float src) {
    csndJNI.Csound_TableCopyIn(swigCPtr, this, table, SWIGTYPE_p_float.getCPtr(src));
  }

  public int CreateGlobalVariable(String name, int nbytes) {
    return csndJNI.Csound_CreateGlobalVariable(swigCPtr, this, name, nbytes);
  }

  public SWIGTYPE_p_void QueryGlobalVariable(String name) {
    long cPtr = csndJNI.Csound_QueryGlobalVariable(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void QueryGlobalVariableNoCheck(String name) {
    long cPtr = csndJNI.Csound_QueryGlobalVariableNoCheck(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public int DestroyGlobalVariable(String name) {
    return csndJNI.Csound_DestroyGlobalVariable(swigCPtr, this, name);
  }

  public SWIGTYPE_p_p_void GetRtRecordUserData() {
    long cPtr = csndJNI.Csound_GetRtRecordUserData(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public SWIGTYPE_p_p_void GetRtPlayUserData() {
    long cPtr = csndJNI.Csound_GetRtPlayUserData(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public int RunUtility(String name, int argc, SWIGTYPE_p_p_char argv) {
    return csndJNI.Csound_RunUtility(swigCPtr, this, name, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public SWIGTYPE_p_p_char ListUtilities() {
    long cPtr = csndJNI.Csound_ListUtilities(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void DeleteUtilityList(SWIGTYPE_p_p_char lst) {
    csndJNI.Csound_DeleteUtilityList(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(lst));
  }

  public String GetUtilityDescription(String utilName) {
    return csndJNI.Csound_GetUtilityDescription(swigCPtr, this, utilName);
  }

  public int GetChannelPtr(SWIGTYPE_p_p_float p, String name, int type) {
    return csndJNI.Csound_GetChannelPtr(swigCPtr, this, SWIGTYPE_p_p_float.getCPtr(p), name, type);
  }

  public int ListChannels(SWIGTYPE_p_p_controlChannelInfo_s lst) {
    return csndJNI.Csound_ListChannels(swigCPtr, this, SWIGTYPE_p_p_controlChannelInfo_s.getCPtr(lst));
  }

  public void DeleteChannelList(controlChannelInfo_t lst) {
    csndJNI.Csound_DeleteChannelList(swigCPtr, this, controlChannelInfo_t.getCPtr(lst), lst);
  }

  public int SetControlChannelHints(String name, controlChannelHints_t hints) {
    return csndJNI.Csound_SetControlChannelHints(swigCPtr, this, name, controlChannelHints_t.getCPtr(hints), hints);
  }

  public int GetControlChannelHints(String name, controlChannelHints_t hints) {
    return csndJNI.Csound_GetControlChannelHints(swigCPtr, this, name, controlChannelHints_t.getCPtr(hints), hints);
  }

  public void SetChannel(String name, double value) {
    csndJNI.Csound_SetChannel__SWIG_0(swigCPtr, this, name, value);
  }

  public void SetChannel(String name, String string) {
    csndJNI.Csound_SetChannel__SWIG_1(swigCPtr, this, name, string);
  }

  public void SetChannel(String name, SWIGTYPE_p_float samples) {
    csndJNI.Csound_SetChannel__SWIG_2(swigCPtr, this, name, SWIGTYPE_p_float.getCPtr(samples));
  }

  public float GetChannel(String name, SWIGTYPE_p_int err) {
    return csndJNI.Csound_GetChannel__SWIG_0(swigCPtr, this, name, SWIGTYPE_p_int.getCPtr(err));
  }

  public float GetChannel(String name) {
    return csndJNI.Csound_GetChannel__SWIG_1(swigCPtr, this, name);
  }

  public void GetStringChannel(String name, String string) {
    csndJNI.Csound_GetStringChannel(swigCPtr, this, name, string);
  }

  public void GetAudioChannel(String name, SWIGTYPE_p_float samples) {
    csndJNI.Csound_GetAudioChannel(swigCPtr, this, name, SWIGTYPE_p_float.getCPtr(samples));
  }

  public int PvsinSet(PVSDATEXT value, String name) {
    return csndJNI.Csound_PvsinSet(swigCPtr, this, PVSDATEXT.getCPtr(value), value, name);
  }

  public int PvsoutGet(PVSDATEXT value, String name) {
    return csndJNI.Csound_PvsoutGet(swigCPtr, this, PVSDATEXT.getCPtr(value), value, name);
  }

  public void SetInputChannelCallback(SWIGTYPE_p_f_p_CSOUND__p_q_const__char_p_void_p_q_const__void__void inputChannelCalback) {
    csndJNI.Csound_SetInputChannelCallback(swigCPtr, this, SWIGTYPE_p_f_p_CSOUND__p_q_const__char_p_void_p_q_const__void__void.getCPtr(inputChannelCalback));
  }

  public void SetOutputChannelCallback(SWIGTYPE_p_f_p_CSOUND__p_q_const__char_p_void_p_q_const__void__void outputChannelCalback) {
    csndJNI.Csound_SetOutputChannelCallback(swigCPtr, this, SWIGTYPE_p_f_p_CSOUND__p_q_const__char_p_void_p_q_const__void__void.getCPtr(outputChannelCalback));
  }

  public Csound() {
    this(csndJNI.new_Csound__SWIG_0(), true);
  }

  public Csound(SWIGTYPE_p_void hostData) {
    this(csndJNI.new_Csound__SWIG_1(SWIGTYPE_p_void.getCPtr(hostData)), true);
  }

  public void CreateMessageBuffer(int toStdOut) {
    csndJNI.Csound_CreateMessageBuffer(swigCPtr, this, toStdOut);
  }

  public String GetFirstMessage() {
    return csndJNI.Csound_GetFirstMessage(swigCPtr, this);
  }

  public int GetFirstMessageAttr() {
    return csndJNI.Csound_GetFirstMessageAttr(swigCPtr, this);
  }

  public void PopFirstMessage() {
    csndJNI.Csound_PopFirstMessage(swigCPtr, this);
  }

  public int GetMessageCnt() {
    return csndJNI.Csound_GetMessageCnt(swigCPtr, this);
  }

  public void DestroyMessageBuffer() {
    csndJNI.Csound_DestroyMessageBuffer(swigCPtr, this);
  }

  public void AddSpinSample(int frame, int channel, float sample) {
    csndJNI.Csound_AddSpinSample(swigCPtr, this, frame, channel, sample);
  }

  public float GetSpoutSample(int frame, int channel) {
    return csndJNI.Csound_GetSpoutSample(swigCPtr, this, frame, channel);
  }

}
