/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundRandMTState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundRandMTState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundRandMTState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundRandMTState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMti(int value) {
    csndJNI.CsoundRandMTState_mti_set(swigCPtr, this, value);
  }

  public int getMti() {
    return csndJNI.CsoundRandMTState_mti_get(swigCPtr, this);
  }

  public void setMt(SWIGTYPE_p_unsigned_int value) {
    csndJNI.CsoundRandMTState_mt_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getMt() {
    long cPtr = csndJNI.CsoundRandMTState_mt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public CsoundRandMTState() {
    this(csndJNI.new_CsoundRandMTState(), true);
  }

}
