/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundFile {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLibraryFilename(String value) {
    csndJNI.CsoundFile_libraryFilename_set(swigCPtr, this, value);
  }

  public String getLibraryFilename() {
    return csndJNI.CsoundFile_libraryFilename_get(swigCPtr, this);
  }

  public void setArrangement(SWIGTYPE_p_std__vectorT_std__string_t value) {
    csndJNI.CsoundFile_arrangement_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getArrangement() {
    long cPtr = csndJNI.CsoundFile_arrangement_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public CsoundFile() {
    this(csndJNI.new_CsoundFile(), true);
  }

  public String generateFilename() {
    return csndJNI.CsoundFile_generateFilename(swigCPtr, this);
  }

  public String getFilename() {
    return csndJNI.CsoundFile_getFilename(swigCPtr, this);
  }

  public void setFilename(String name) {
    csndJNI.CsoundFile_setFilename(swigCPtr, this, name);
  }

  public int load(String filename) {
    return csndJNI.CsoundFile_load__SWIG_0(swigCPtr, this, filename);
  }

  public int load(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_load__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int save(String filename) {
    return csndJNI.CsoundFile_save__SWIG_0(swigCPtr, this, filename);
  }

  public int save(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_save__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public int importFile(String filename) {
    return csndJNI.CsoundFile_importFile__SWIG_0(swigCPtr, this, filename);
  }

  public int importFile(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_importFile__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int importCommand(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_importCommand(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int exportCommand(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_exportCommand(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public int importOrchestra(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_importOrchestra(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int exportOrchestra(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_exportOrchestra(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public int importScore(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_importScore(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int exportScore(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_exportScore(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public int importArrangement(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_importArrangement(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int exportArrangement(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_exportArrangement(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public int exportArrangementForPerformance(String filename) {
    return csndJNI.CsoundFile_exportArrangementForPerformance__SWIG_0(swigCPtr, this, filename);
  }

  public int exportArrangementForPerformance(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_exportArrangementForPerformance__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public int importMidifile(SWIGTYPE_p_std__istream stream) {
    return csndJNI.CsoundFile_importMidifile(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(stream));
  }

  public int exportMidifile(SWIGTYPE_p_std__ostream stream) {
    return csndJNI.CsoundFile_exportMidifile(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public String getCommand() {
    return csndJNI.CsoundFile_getCommand(swigCPtr, this);
  }

  public void setCommand(String commandLine) {
    csndJNI.CsoundFile_setCommand(swigCPtr, this, commandLine);
  }

  public String getOrcFilename() {
    return csndJNI.CsoundFile_getOrcFilename(swigCPtr, this);
  }

  public String getScoFilename() {
    return csndJNI.CsoundFile_getScoFilename(swigCPtr, this);
  }

  public String getMidiFilename() {
    return csndJNI.CsoundFile_getMidiFilename(swigCPtr, this);
  }

  public String getOutputSoundfileName() {
    return csndJNI.CsoundFile_getOutputSoundfileName(swigCPtr, this);
  }

  public String getOrchestra() {
    return csndJNI.CsoundFile_getOrchestra(swigCPtr, this);
  }

  public void setOrchestra(String orchestra) {
    csndJNI.CsoundFile_setOrchestra(swigCPtr, this, orchestra);
  }

  public int getInstrumentCount() {
    return csndJNI.CsoundFile_getInstrumentCount(swigCPtr, this);
  }

  public String getOrchestraHeader() {
    return csndJNI.CsoundFile_getOrchestraHeader(swigCPtr, this);
  }

  public boolean getInstrument(int number, SWIGTYPE_p_std__string definition) {
    return csndJNI.CsoundFile_getInstrument__SWIG_0(swigCPtr, this, number, SWIGTYPE_p_std__string.getCPtr(definition));
  }

  public boolean getInstrument(String name, SWIGTYPE_p_std__string definition) {
    return csndJNI.CsoundFile_getInstrument__SWIG_1(swigCPtr, this, name, SWIGTYPE_p_std__string.getCPtr(definition));
  }

  public String getInstrument(String name) {
    return csndJNI.CsoundFile_getInstrument__SWIG_2(swigCPtr, this, name);
  }

  public String getInstrument(int number) {
    return csndJNI.CsoundFile_getInstrument__SWIG_3(swigCPtr, this, number);
  }

  public String getInstrumentBody(String name) {
    return csndJNI.CsoundFile_getInstrumentBody__SWIG_0(swigCPtr, this, name);
  }

  public String getInstrumentBody(int number) {
    return csndJNI.CsoundFile_getInstrumentBody__SWIG_1(swigCPtr, this, number);
  }

  public IntToStringMap getInstrumentNames() {
    return new IntToStringMap(csndJNI.CsoundFile_getInstrumentNames(swigCPtr, this), true);
  }

  public double getInstrumentNumber(String name) {
    return csndJNI.CsoundFile_getInstrumentNumber(swigCPtr, this, name);
  }

  public String getScore() {
    return csndJNI.CsoundFile_getScore(swigCPtr, this);
  }

  public void setScore(String score) {
    csndJNI.CsoundFile_setScore(swigCPtr, this, score);
  }

  public int getArrangementCount() {
    return csndJNI.CsoundFile_getArrangementCount(swigCPtr, this);
  }

  public String getArrangement(int index) {
    return csndJNI.CsoundFile_getArrangement(swigCPtr, this, index);
  }

  public void addArrangement(String instrument) {
    csndJNI.CsoundFile_addArrangement(swigCPtr, this, instrument);
  }

  public void setArrangement(int index, String instrument) {
    csndJNI.CsoundFile_setArrangement(swigCPtr, this, index, instrument);
  }

  public void insertArrangement(int index, String instrument) {
    csndJNI.CsoundFile_insertArrangement(swigCPtr, this, index, instrument);
  }

  public void removeArrangement(int index) {
    csndJNI.CsoundFile_removeArrangement__SWIG_0(swigCPtr, this, index);
  }

  public void setCSD(String xml) {
    csndJNI.CsoundFile_setCSD(swigCPtr, this, xml);
  }

  public String getCSD() {
    return csndJNI.CsoundFile_getCSD(swigCPtr, this);
  }

  public void addScoreLine(String line) {
    csndJNI.CsoundFile_addScoreLine(swigCPtr, this, line);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5, double p6, double p7, double p8, double p9, double p10, double p11) {
    csndJNI.CsoundFile_addNote__SWIG_0(swigCPtr, this, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5, double p6, double p7, double p8, double p9, double p10) {
    csndJNI.CsoundFile_addNote__SWIG_1(swigCPtr, this, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5, double p6, double p7, double p8, double p9) {
    csndJNI.CsoundFile_addNote__SWIG_2(swigCPtr, this, p1, p2, p3, p4, p5, p6, p7, p8, p9);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5, double p6, double p7, double p8) {
    csndJNI.CsoundFile_addNote__SWIG_3(swigCPtr, this, p1, p2, p3, p4, p5, p6, p7, p8);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5, double p6, double p7) {
    csndJNI.CsoundFile_addNote__SWIG_4(swigCPtr, this, p1, p2, p3, p4, p5, p6, p7);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5, double p6) {
    csndJNI.CsoundFile_addNote__SWIG_5(swigCPtr, this, p1, p2, p3, p4, p5, p6);
  }

  public void addNote(double p1, double p2, double p3, double p4, double p5) {
    csndJNI.CsoundFile_addNote__SWIG_6(swigCPtr, this, p1, p2, p3, p4, p5);
  }

  public void addNote(double p1, double p2, double p3, double p4) {
    csndJNI.CsoundFile_addNote__SWIG_7(swigCPtr, this, p1, p2, p3, p4);
  }

  public void addNote(double p1, double p2, double p3) {
    csndJNI.CsoundFile_addNote__SWIG_8(swigCPtr, this, p1, p2, p3);
  }

  public boolean exportForPerformance() {
    return csndJNI.CsoundFile_exportForPerformance(swigCPtr, this);
  }

  public void removeAll() {
    csndJNI.CsoundFile_removeAll(swigCPtr, this);
  }

  public void removeCommand() {
    csndJNI.CsoundFile_removeCommand(swigCPtr, this);
  }

  public void removeOrchestra() {
    csndJNI.CsoundFile_removeOrchestra(swigCPtr, this);
  }

  public void removeScore() {
    csndJNI.CsoundFile_removeScore(swigCPtr, this);
  }

  public void removeArrangement() {
    csndJNI.CsoundFile_removeArrangement__SWIG_1(swigCPtr, this);
  }

  public void removeMidifile() {
    csndJNI.CsoundFile_removeMidifile(swigCPtr, this);
  }

  public boolean loadOrcLibrary(String filename) {
    return csndJNI.CsoundFile_loadOrcLibrary__SWIG_0(swigCPtr, this, filename);
  }

  public boolean loadOrcLibrary() {
    return csndJNI.CsoundFile_loadOrcLibrary__SWIG_1(swigCPtr, this);
  }

}
