/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundArgVList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundArgVList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundArgVList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundArgVList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int argc() {
    return csndJNI.CsoundArgVList_argc(swigCPtr, this);
  }

  public SWIGTYPE_p_p_char argv() {
    long cPtr = csndJNI.CsoundArgVList_argv__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public String argv(int ndx) {
    return csndJNI.CsoundArgVList_argv__SWIG_1(swigCPtr, this, ndx);
  }

  public void Insert(int ndx, String s) {
    csndJNI.CsoundArgVList_Insert(swigCPtr, this, ndx, s);
  }

  public void Append(String s) {
    csndJNI.CsoundArgVList_Append(swigCPtr, this, s);
  }

  public void Clear() {
    csndJNI.CsoundArgVList_Clear(swigCPtr, this);
  }

  public CsoundArgVList() {
    this(csndJNI.new_CsoundArgVList(), true);
  }

}
