/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundTimer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundTimer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundTimer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundTimer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double GetRealTime() {
    return csndJNI.CsoundTimer_GetRealTime(swigCPtr, this);
  }

  public double GetCPUTime() {
    return csndJNI.CsoundTimer_GetCPUTime(swigCPtr, this);
  }

  public void Reset() {
    csndJNI.CsoundTimer_Reset(swigCPtr, this);
  }

  public CsoundTimer() {
    this(csndJNI.new_CsoundTimer(), true);
  }

}
