/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundUtilityList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundUtilityList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundUtilityList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundUtilityList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int Count() {
    return csndJNI.CsoundUtilityList_Count(swigCPtr, this);
  }

  public String Name(int ndx) {
    return csndJNI.CsoundUtilityList_Name(swigCPtr, this, ndx);
  }

  public void Clear() {
    csndJNI.CsoundUtilityList_Clear(swigCPtr, this);
  }

  public CsoundUtilityList(SWIGTYPE_p_CSOUND_ csound) {
    this(csndJNI.new_CsoundUtilityList__SWIG_0(SWIGTYPE_p_CSOUND_.getCPtr(csound)), true);
  }

  public CsoundUtilityList(Csound csound) {
    this(csndJNI.new_CsoundUtilityList__SWIG_1(Csound.getCPtr(csound), csound), true);
  }

}
