/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public final class CSOUND_STATUS {
  public final static CSOUND_STATUS CSOUND_SUCCESS = new CSOUND_STATUS("CSOUND_SUCCESS", csndJNI.CSOUND_SUCCESS_get());
  public final static CSOUND_STATUS CSOUND_ERROR = new CSOUND_STATUS("CSOUND_ERROR", csndJNI.CSOUND_ERROR_get());
  public final static CSOUND_STATUS CSOUND_INITIALIZATION = new CSOUND_STATUS("CSOUND_INITIALIZATION", csndJNI.CSOUND_INITIALIZATION_get());
  public final static CSOUND_STATUS CSOUND_PERFORMANCE = new CSOUND_STATUS("CSOUND_PERFORMANCE", csndJNI.CSOUND_PERFORMANCE_get());
  public final static CSOUND_STATUS CSOUND_MEMORY = new CSOUND_STATUS("CSOUND_MEMORY", csndJNI.CSOUND_MEMORY_get());
  public final static CSOUND_STATUS CSOUND_SIGNAL = new CSOUND_STATUS("CSOUND_SIGNAL", csndJNI.CSOUND_SIGNAL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CSOUND_STATUS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CSOUND_STATUS.class + " with value " + swigValue);
  }

  private CSOUND_STATUS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CSOUND_STATUS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CSOUND_STATUS(String swigName, CSOUND_STATUS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CSOUND_STATUS[] swigValues = { CSOUND_SUCCESS, CSOUND_ERROR, CSOUND_INITIALIZATION, CSOUND_PERFORMANCE, CSOUND_MEMORY, CSOUND_SIGNAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

