/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundRandMT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundRandMT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundRandMT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundRandMT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long Random() {
    return csndJNI.CsoundRandMT_Random(swigCPtr, this);
  }

  public void Seed(long seedVal) {
    csndJNI.CsoundRandMT_Seed__SWIG_0(swigCPtr, this, seedVal);
  }

  public void Seed(SWIGTYPE_p_unsigned_int initKey, int keyLength) {
    csndJNI.CsoundRandMT_Seed__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(initKey), keyLength);
  }

  public CsoundRandMT() {
    this(csndJNI.new_CsoundRandMT__SWIG_0(), true);
  }

  public CsoundRandMT(long seedVal) {
    this(csndJNI.new_CsoundRandMT__SWIG_1(seedVal), true);
  }

  public CsoundRandMT(SWIGTYPE_p_unsigned_int initKey, int keyLength) {
    this(csndJNI.new_CsoundRandMT__SWIG_2(SWIGTYPE_p_unsigned_int.getCPtr(initKey), keyLength), true);
  }

}
