/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundOpcodeList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundOpcodeList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundOpcodeList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundOpcodeList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int Count() {
    return csndJNI.CsoundOpcodeList_Count(swigCPtr, this);
  }

  public String Name(int ndx) {
    return csndJNI.CsoundOpcodeList_Name(swigCPtr, this, ndx);
  }

  public String OutTypes(int ndx) {
    return csndJNI.CsoundOpcodeList_OutTypes(swigCPtr, this, ndx);
  }

  public String InTypes(int ndx) {
    return csndJNI.CsoundOpcodeList_InTypes(swigCPtr, this, ndx);
  }

  public void Clear() {
    csndJNI.CsoundOpcodeList_Clear(swigCPtr, this);
  }

  public CsoundOpcodeList(SWIGTYPE_p_CSOUND_ csound) {
    this(csndJNI.new_CsoundOpcodeList__SWIG_0(SWIGTYPE_p_CSOUND_.getCPtr(csound)), true);
  }

  public CsoundOpcodeList(Csound csound) {
    this(csndJNI.new_CsoundOpcodeList__SWIG_1(Csound.getCPtr(csound), csound), true);
  }

}
