/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class CsoundMidiOutputStream extends CsoundMidiOutputBuffer {
  private transient long swigCPtr;

  protected CsoundMidiOutputStream(long cPtr, boolean cMemoryOwn) {
    super(csndJNI.CsoundMidiOutputStream_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundMidiOutputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundMidiOutputStream(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CsoundMidiOutputStream(SWIGTYPE_p_CSOUND_ csound) {
    this(csndJNI.new_CsoundMidiOutputStream__SWIG_0(SWIGTYPE_p_CSOUND_.getCPtr(csound)), true);
  }

  public CsoundMidiOutputStream(Csound csound) {
    this(csndJNI.new_CsoundMidiOutputStream__SWIG_1(Csound.getCPtr(csound), csound), true);
  }

  public void EnableMidiOutput(CsoundArgVList argv) {
    csndJNI.CsoundMidiOutputStream_EnableMidiOutput(swigCPtr, this, CsoundArgVList.getCPtr(argv), argv);
  }

}
