/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class csRtAudioParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected csRtAudioParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(csRtAudioParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_csRtAudioParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDevName(String value) {
    csndJNI.csRtAudioParams_devName_set(swigCPtr, this, value);
  }

  public String getDevName() {
    return csndJNI.csRtAudioParams_devName_get(swigCPtr, this);
  }

  public void setDevNum(int value) {
    csndJNI.csRtAudioParams_devNum_set(swigCPtr, this, value);
  }

  public int getDevNum() {
    return csndJNI.csRtAudioParams_devNum_get(swigCPtr, this);
  }

  public void setBufSamp_SW(long value) {
    csndJNI.csRtAudioParams_bufSamp_SW_set(swigCPtr, this, value);
  }

  public long getBufSamp_SW() {
    return csndJNI.csRtAudioParams_bufSamp_SW_get(swigCPtr, this);
  }

  public void setBufSamp_HW(int value) {
    csndJNI.csRtAudioParams_bufSamp_HW_set(swigCPtr, this, value);
  }

  public int getBufSamp_HW() {
    return csndJNI.csRtAudioParams_bufSamp_HW_get(swigCPtr, this);
  }

  public void setNChannels(int value) {
    csndJNI.csRtAudioParams_nChannels_set(swigCPtr, this, value);
  }

  public int getNChannels() {
    return csndJNI.csRtAudioParams_nChannels_get(swigCPtr, this);
  }

  public void setSampleFormat(int value) {
    csndJNI.csRtAudioParams_sampleFormat_set(swigCPtr, this, value);
  }

  public int getSampleFormat() {
    return csndJNI.csRtAudioParams_sampleFormat_get(swigCPtr, this);
  }

  public void setSampleRate(float value) {
    csndJNI.csRtAudioParams_sampleRate_set(swigCPtr, this, value);
  }

  public float getSampleRate() {
    return csndJNI.csRtAudioParams_sampleRate_get(swigCPtr, this);
  }

  public csRtAudioParams() {
    this(csndJNI.new_csRtAudioParams(), true);
  }

}
