/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class MyfltVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MyfltVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MyfltVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_MyfltVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MyfltVector() {
    this(csndJNI.new_MyfltVector__SWIG_0(), true);
  }

  public MyfltVector(int n) {
    this(csndJNI.new_MyfltVector__SWIG_1(n), true);
  }

  public int size() {
    return csndJNI.MyfltVector_size(swigCPtr, this);
  }

  public int capacity() {
    return csndJNI.MyfltVector_capacity(swigCPtr, this);
  }

  public void reserve(int n) {
    csndJNI.MyfltVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return csndJNI.MyfltVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    csndJNI.MyfltVector_clear(swigCPtr, this);
  }

  public void add(float x) {
    csndJNI.MyfltVector_add(swigCPtr, this, x);
  }

  public float get(int i) {
    return csndJNI.MyfltVector_get(swigCPtr, this, i);
  }

  public void set(int i, float val) {
    csndJNI.MyfltVector_set(swigCPtr, this, i, val);
  }

}
