/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class opcodeListEntry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected opcodeListEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(opcodeListEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_opcodeListEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOpname(String value) {
    csndJNI.opcodeListEntry_opname_set(swigCPtr, this, value);
  }

  public String getOpname() {
    return csndJNI.opcodeListEntry_opname_get(swigCPtr, this);
  }

  public void setOutypes(String value) {
    csndJNI.opcodeListEntry_outypes_set(swigCPtr, this, value);
  }

  public String getOutypes() {
    return csndJNI.opcodeListEntry_outypes_get(swigCPtr, this);
  }

  public void setIntypes(String value) {
    csndJNI.opcodeListEntry_intypes_set(swigCPtr, this, value);
  }

  public String getIntypes() {
    return csndJNI.opcodeListEntry_intypes_get(swigCPtr, this);
  }

  public opcodeListEntry() {
    this(csndJNI.new_opcodeListEntry(), true);
  }

}
