/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class ORCTOKEN {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ORCTOKEN(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ORCTOKEN obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_ORCTOKEN(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    csndJNI.ORCTOKEN_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return csndJNI.ORCTOKEN_type_get(swigCPtr, this);
  }

  public void setLexeme(String value) {
    csndJNI.ORCTOKEN_lexeme_set(swigCPtr, this, value);
  }

  public String getLexeme() {
    return csndJNI.ORCTOKEN_lexeme_get(swigCPtr, this);
  }

  public void setValue(int value) {
    csndJNI.ORCTOKEN_value_set(swigCPtr, this, value);
  }

  public int getValue() {
    return csndJNI.ORCTOKEN_value_get(swigCPtr, this);
  }

  public void setFvalue(double value) {
    csndJNI.ORCTOKEN_fvalue_set(swigCPtr, this, value);
  }

  public double getFvalue() {
    return csndJNI.ORCTOKEN_fvalue_get(swigCPtr, this);
  }

  public void setOptype(String value) {
    csndJNI.ORCTOKEN_optype_set(swigCPtr, this, value);
  }

  public String getOptype() {
    return csndJNI.ORCTOKEN_optype_get(swigCPtr, this);
  }

  public void setNext(ORCTOKEN value) {
    csndJNI.ORCTOKEN_next_set(swigCPtr, this, ORCTOKEN.getCPtr(value), value);
  }

  public ORCTOKEN getNext() {
    long cPtr = csndJNI.ORCTOKEN_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ORCTOKEN(cPtr, false);
  }

  public ORCTOKEN() {
    this(csndJNI.new_ORCTOKEN(), true);
  }

}
