/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class RTCLOCK {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RTCLOCK(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RTCLOCK obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_RTCLOCK(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStarttime_real(SWIGTYPE_p_int_least64_t value) {
    csndJNI.RTCLOCK_starttime_real_set(swigCPtr, this, SWIGTYPE_p_int_least64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int_least64_t getStarttime_real() {
    return new SWIGTYPE_p_int_least64_t(csndJNI.RTCLOCK_starttime_real_get(swigCPtr, this), true);
  }

  public void setStarttime_CPU(SWIGTYPE_p_int_least64_t value) {
    csndJNI.RTCLOCK_starttime_CPU_set(swigCPtr, this, SWIGTYPE_p_int_least64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int_least64_t getStarttime_CPU() {
    return new SWIGTYPE_p_int_least64_t(csndJNI.RTCLOCK_starttime_CPU_get(swigCPtr, this), true);
  }

  public RTCLOCK() {
    this(csndJNI.new_RTCLOCK(), true);
  }

}
