/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class Soundfile {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Soundfile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Soundfile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_Soundfile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Soundfile() {
    this(csndJNI.new_Soundfile(), true);
  }

  public int getFramesPerSecond() {
    return csndJNI.Soundfile_getFramesPerSecond(swigCPtr, this);
  }

  public void setFramesPerSecond(int framesPerSecond) {
    csndJNI.Soundfile_setFramesPerSecond(swigCPtr, this, framesPerSecond);
  }

  public int getChannelsPerFrame() {
    return csndJNI.Soundfile_getChannelsPerFrame(swigCPtr, this);
  }

  public void setChannelsPerFrame(int channelsPerFrame) {
    csndJNI.Soundfile_setChannelsPerFrame(swigCPtr, this, channelsPerFrame);
  }

  public int getFormat() {
    return csndJNI.Soundfile_getFormat(swigCPtr, this);
  }

  public void setFormat(int format) {
    csndJNI.Soundfile_setFormat(swigCPtr, this, format);
  }

  public int getFrames() {
    return csndJNI.Soundfile_getFrames(swigCPtr, this);
  }

  public int open(String filename) {
    return csndJNI.Soundfile_open(swigCPtr, this, filename);
  }

  public int create(String filename, int framesPerSecond, int channelsPerFrame, int format) {
    return csndJNI.Soundfile_create__SWIG_0(swigCPtr, this, filename, framesPerSecond, channelsPerFrame, format);
  }

  public int create(String filename, int framesPerSecond, int channelsPerFrame) {
    return csndJNI.Soundfile_create__SWIG_1(swigCPtr, this, filename, framesPerSecond, channelsPerFrame);
  }

  public int create(String filename, int framesPerSecond) {
    return csndJNI.Soundfile_create__SWIG_2(swigCPtr, this, filename, framesPerSecond);
  }

  public int create(String filename) {
    return csndJNI.Soundfile_create__SWIG_3(swigCPtr, this, filename);
  }

  public int seek(int frames, int whence) {
    return csndJNI.Soundfile_seek__SWIG_0(swigCPtr, this, frames, whence);
  }

  public int seek(int frames) {
    return csndJNI.Soundfile_seek__SWIG_1(swigCPtr, this, frames);
  }

  public double seekSeconds(double seconds, int whence) {
    return csndJNI.Soundfile_seekSeconds__SWIG_0(swigCPtr, this, seconds, whence);
  }

  public double seekSeconds(double seconds) {
    return csndJNI.Soundfile_seekSeconds__SWIG_1(swigCPtr, this, seconds);
  }

  public int readFrame(SWIGTYPE_p_double outputFrame) {
    return csndJNI.Soundfile_readFrame(swigCPtr, this, SWIGTYPE_p_double.getCPtr(outputFrame));
  }

  public int writeFrame(SWIGTYPE_p_double inputFrame) {
    return csndJNI.Soundfile_writeFrame(swigCPtr, this, SWIGTYPE_p_double.getCPtr(inputFrame));
  }

  public int readFrames(SWIGTYPE_p_double outputFrames, int samples) {
    return csndJNI.Soundfile_readFrames(swigCPtr, this, SWIGTYPE_p_double.getCPtr(outputFrames), samples);
  }

  public int writeFrames(SWIGTYPE_p_double inputFrames, int samples) {
    return csndJNI.Soundfile_writeFrames(swigCPtr, this, SWIGTYPE_p_double.getCPtr(inputFrames), samples);
  }

  public int mixFrames(SWIGTYPE_p_double inputFrames, int samples, SWIGTYPE_p_double mixedFrames) {
    return csndJNI.Soundfile_mixFrames(swigCPtr, this, SWIGTYPE_p_double.getCPtr(inputFrames), samples, SWIGTYPE_p_double.getCPtr(mixedFrames));
  }

  public void updateHeader() {
    csndJNI.Soundfile_updateHeader(swigCPtr, this);
  }

  public int close() {
    return csndJNI.Soundfile_close(swigCPtr, this);
  }

  public void error() {
    csndJNI.Soundfile_error(swigCPtr, this);
  }

  public void blank(double duration) {
    csndJNI.Soundfile_blank(swigCPtr, this, duration);
  }

}
