/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

public class TREE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TREE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TREE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_TREE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    csndJNI.TREE_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return csndJNI.TREE_type_get(swigCPtr, this);
  }

  public void setValue(ORCTOKEN value) {
    csndJNI.TREE_value_set(swigCPtr, this, ORCTOKEN.getCPtr(value), value);
  }

  public ORCTOKEN getValue() {
    long cPtr = csndJNI.TREE_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ORCTOKEN(cPtr, false);
  }

  public void setRate(int value) {
    csndJNI.TREE_rate_set(swigCPtr, this, value);
  }

  public int getRate() {
    return csndJNI.TREE_rate_get(swigCPtr, this);
  }

  public void setLen(int value) {
    csndJNI.TREE_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return csndJNI.TREE_len_get(swigCPtr, this);
  }

  public void setLine(int value) {
    csndJNI.TREE_line_set(swigCPtr, this, value);
  }

  public int getLine() {
    return csndJNI.TREE_line_get(swigCPtr, this);
  }

  public void setLocn(SWIGTYPE_p_uint64_t value) {
    csndJNI.TREE_locn_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getLocn() {
    return new SWIGTYPE_p_uint64_t(csndJNI.TREE_locn_get(swigCPtr, this), true);
  }

  public void setLeft(TREE value) {
    csndJNI.TREE_left_set(swigCPtr, this, TREE.getCPtr(value), value);
  }

  public TREE getLeft() {
    long cPtr = csndJNI.TREE_left_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TREE(cPtr, false);
  }

  public void setRight(TREE value) {
    csndJNI.TREE_right_set(swigCPtr, this, TREE.getCPtr(value), value);
  }

  public TREE getRight() {
    long cPtr = csndJNI.TREE_right_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TREE(cPtr, false);
  }

  public void setNext(TREE value) {
    csndJNI.TREE_next_set(swigCPtr, this, TREE.getCPtr(value), value);
  }

  public TREE getNext() {
    long cPtr = csndJNI.TREE_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TREE(cPtr, false);
  }

  public void setMarkup(SWIGTYPE_p_void value) {
    csndJNI.TREE_markup_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getMarkup() {
    long cPtr = csndJNI.TREE_markup_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public TREE() {
    this(csndJNI.new_TREE(), true);
  }

}
